bases:
  - ../../common/helm/environments.yaml
  - ../../common/helm/repositories.yaml

templates:
  default: &default
    missingFileHandler: Warn
    values:
      - config/{{`{{ .Release.Name }}`}}/values.yaml
      - config/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml

releases:
  - name: docker-registry
    namespace: default
    chart: twuni/docker-registry
    version: 2.1.0
    <<: *default
